### ISSUE TITLE
General comment, use aws sdk2 instead

### ISSUE THREAD

**Issue by rleibman** [aws4s/aws4s#12]
Thank you for the attempt, but ... I'm sorry, but I think the effort sounds futile, you'll end up chasing apis, aws is changing way too quickly. 
You only have 2 services, out of tens that aws provides. 
I see a strong need for aws4s, but Instead of building it from scratch I'd write wrappers and helpers that use the aws version 2 sdk (which is still in beta, but is much more asynchronous that the previous versions). 
A utility For example that I use a lot is
```
  def whileInProgress[Request <: AmazonWebServiceRequest, Response](
      method: Request => java.util.concurrent.CompletableFuture[Response],
      request: Request,
      isInProgress: Response ⇒ Boolean,
      duration: Duration = 30 seconds)(implicit actorSystem: ActorSystem): Future[Response] = {

    import actorSystem.dispatcher
    val log = Logging(actorSystem, getClass)

    def loop(): Future[Response] = {
      val fut = method(request).toScala
      fut.flatMap { response =>
        if (isInProgress(response)) {
          log.debug(s"Request ${request.getClass.getName} in progress: ${response}")
          Thread.sleep(duration.toMillis)
          loop
        } else {
          Future.successful(response)
        }
      }
    }

    loop
  }
```
This allows me to create a future that will callback after a long running aws process (e.g. a CloudFormation stack creation)

**Comment by amrhassan** [comment]
Thank you for your comment. Of course one could jump through hoops to wrap Java APIs and make sure it's all nice and conforming, but I've chosen to build this on top of the safer and more predictable APIs of http4s, fs2, and cats. Predictable and safer APIs tend to be less work in the long run and easier to maintain in the face of ever changing requirements imho :)

**Comment by rleibman** [comment]
Yeah, but think about it, you only have 2 services written, it's going to take you forever to get even a portion of aws done, and by that time they'll change it and you'll have to chase it. I currently use (all from scala) ec2, s3, cloudformation, route53, rds, iam: if I was starting from scratch today I'd look at your project and realize that you can't do what I need. 
Please understand, I really mean no disrespect, I have my own open source projects and fall in love with them, these are just some thoughts, I totally thank you and every single person willing to put their code out there.
Good luck!

**Comment by rleibman** [comment]
I wonder... the aws sdk2 also has a pluggable http client layer, so you could internally force it to use http4s if you wanted.
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

**Comment by amrhassan** [comment]
I see your concerns and I appreciate you trying to help. I will do my best to cover the most popular services for now in an adequate enough manner. Hopefully this will be of use to someone with intersecting use cases with mine and with similar safety/maintainability requirements. There are other projects out there that wrap the Java SDK and I'm sure they'll catch up with the new SDK soon enough, but this is not the approach that I'm going to pursue here at the moment.

Thanks again for your helpful comments and suggestions. I'm going to close this issue but feel free to create new ones with feature requirements, questions or if you're having trouble using this project.
