### ISSUE TITLE
S3 upload fails when body at least 10kb in size

### ISSUE THREAD

**Issue by Malax** [aws4s/aws4s#27]
When the body of a `putObject` is 10kb or larger in size, the process will fail with:

```
org.aws4s.ErrorResponse: Error response:
status:   501 Not Implemented,
type:
code:     NotImplemented
message:  A header you provided implies functionality that is not implemented
```

I tracked the issue down and found out that the `Transfer-Encoding` header caues the problem. Blaze internally creates chunks of 10kb, that's why this is the magic limit. AWS seems to support chunked uploads as long as the request bodies are signed and the `Content-Length` header is provided, even with chunked encoding.

This issue can be easily reproduced by increasing the `data` field size to 10kb in `org.aws4s.s3.S3SmokeTest`.

Unfortunately I don't know how to work around this issue, otherwise I would have created a PR with a fix.

**Comment by amrhassan** [comment]
Thank you for investigating and reporting this.

It seems that my implementation is rather naive and only works with the single chunk as you said. I can make it work by running the payload stream entirely first then pass the resulting bytes to http4s which treats it then as a single unchunked request, which works.

This of course assumes that the payload is small enough to fit all in memory. I will change it to be like that while I investigate further into how I can make the chunked uploading work.

**Comment by amrhassan** [comment]
I just made a release for `0.6.1` with the fix that you can use for now if you have enough memory. Hopefully the chunked uploading should be done soon and would require no breaking API changes.
