### ISSUE TITLE
SQS MessageBody size validation is incorrect

### ISSUE THREAD

**Issue by fredshonorio** [aws4s/aws4s#32]
If I'm reading the code correctly,  [MessageBody](https://github.com/aws4s/aws4s/blob/42ed4d23bf9e4199fce989c343029141897a8e87/src/main/scala/org/aws4s/sqs/MessageBody.scala) expects a string up to 256 characters in length, this is incorrect according to the [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html#limits-messages), it's 256kb not bytes.

Additionally, the minimum is 1, not 0, and measuring by character length is certain to cause issues when non-ascii characters are in the message.

I could PR a fix if you'd like.

**Comment by fredshonorio** [comment]
I guess measuring by byte size is not really important because the queue can be configured for smaller sizes anyway (the maximum size is queue dependent).

**Comment by amrhassan** [comment]
Thank you for reporting. I guess validating against the maximum size wouldn't hurt.

I'll publish a fix in a few minutes..
